### ISSUE TITLE
Can't Generate DB

### ISSUE THREAD

**Issue by caxanga334** [FlaminSarge/tf2idb#19]
After the jungle inferno update I can't generate the db file. I get this error.
```
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: PATH\tf2idb.py =============
Traceback (most recent call last):
  File "PATH\tf2idb.py", line 187, in main
    i.get('holiday_restriction'), has_string_attribute, i.get('propername'))
sqlite3.IntegrityError: NOT NULL constraint failed: new_tf2idb_item.item_name
25000
Traceback (most recent call last):
  File "PATH\tf2idb.py", line 228, in <module>
    main()
  File "PATH\tf2idb.py", line 187, in main
    i.get('holiday_restriction'), has_string_attribute, i.get('propername'))
sqlite3.IntegrityError: NOT NULL constraint failed: new_tf2idb_item.item_name
```

**Comment by fakuivan** [comment]
Remove ``NOT NULL`` from [tf2idb.py at Line 78](https://github.com/FlaminSarge/tf2idb/blob/d859e32a0af1dd3e68363d633310f02b77e37d3c/db/tf2idb.py#L78), the old, deprecated contracts don't have an "item_name" field since the Jungle Inferno update.
